version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
    environment:
      WATCHPACK_POLLING: 'true'
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/itnihongo_db
    env_file:
      - ./backend/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
