version: '3.8'

services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      WATCHPACK_POLLING: "true"

    depends_on:
      - backend
    restart: always
