version: "3.8"

services:
  backend:
    image: thanh2910/itnihongo-backend
    build:
      context: backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      POSTGRES_CONNECTION: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
    restart: always

  frontend:
    image: thanh2910/itnihongo-frontend
    build:
      context: frontend
      target: nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      WATCHPACK_POLLING: "true"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/itnihongo_db

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
